export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCEEDED = 'FETCH_USER_SUCCEEDED';

export const SAVE_CALCULATOR_DATA = 'SAVE_CALCULATOR_DATA';
export const SAVE_CALCULATOR_DATA_SUCCEEDED = 'SAVE_CALCULATOR_DATA_SUCCEEDED';

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const KILL_SNACKBAR = 'KILL_SNACKBAR';
